# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-14 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_package', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='kfisher', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
